name: Build Android APK (Expo)

on:
  workflow_dispatch:

jobs:
  build-android:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: 🧩 Checkout repository
        uses: actions/checkout@v4

      - name: 🟩 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 🧰 Install dependencies
        run: |
          npm install -g eas-cli
          npm ci

      - name: 🗑️ Remove expo-barcode-scanner (incompatible)
        run: |
          npm uninstall expo-barcode-scanner || true

      - name: 🔧 Clean and verify dependencies
        run: |
          npm install
          npx expo install --fix

      - name: ⚙️ Prebuild native Android project
        run: |
          npx expo prebuild --platform android --clean
        env:
          EXPO_NO_TELEMETRY: 1

      - name: 🔨 Make Gradlew executable
        run: |
          cd android
          chmod +x gradlew

      - name: 📦 Build Android APK
        run: |
          cd android
          ./gradlew assembleRelease --no-daemon --stacktrace
        env:
          EXPO_NO_DOTENV: 1

      - name: 🕵️ Find generated APK path
        id: find_apk
        run: |
          APK_PATH=$(find android/app/build/outputs/apk/release -name "*.apk" | head -n 1)
          echo "apk_path=$APK_PATH" >> $GITHUB_OUTPUT
          echo "Found APK at: $APK_PATH"

      - name: 🏷️ Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: build-${{ github.run_number }}
          name: "Build ${{ github.run_number }}"
          draft: false
          prerelease: false
          files: ${{ steps.find_apk.outputs.apk_path }}
        env:
          GITHUB_TOKEN: ${{ secrets.ACCOUNT_TOKEN }}
